In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r'C:\Users\hp\Documents\Python\Movie_Rating_miniProject\movies.csv')

In [30]:
df

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...
246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000,216639112,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000,14480,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [5]:
df.columns

Index(['rank', 'name', 'year', 'rating', 'genre', 'certificate', 'run_time',
       'tagline', 'budget', 'box_office', 'casts', 'directors', 'writers'],
      dtype='object')

In [6]:
for col in df:
    print(f'{col} -> {df[col].nunique()}')

rank -> 250
name -> 250
year -> 86
rating -> 13
genre -> 104
certificate -> 15
run_time -> 102
tagline -> 250
budget -> 128
box_office -> 221
casts -> 250
directors -> 160
writers -> 233

In [31]:
df.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            241, 242, 243, 244, 245, 246, 247, 248, 249, 250],
           dtype='int64', name='rank', length=250)

In [8]:
df.loc[1]

rank                                                           2
name                                               The Godfather
year                                                        1972
rating                                                       9.2
genre                                                Crime,Drama
certificate                                                    R
run_time                                                  2h 55m
tagline                               An offer you can't refuse.
budget                                                   6000000
box_office                                             250341816
casts          Marlon Brando,Al Pacino,James Caan,Diane Keato...
directors                                   Francis Ford Coppola
writers                          Mario Puzo,Francis Ford Coppola
Name: 1, dtype: object

In [14]:
df.iloc[1]

rank                                                           2
name                                               The Godfather
year                                                        1972
rating                                                       9.2
genre                                                Crime,Drama
certificate                                                    R
run_time                                                  2h 55m
tagline                               An offer you can't refuse.
budget                                                   6000000
box_office                                             250341816
casts          Marlon Brando,Al Pacino,James Caan,Diane Keato...
directors                                   Francis Ford Coppola
writers                          Mario Puzo,Francis Ford Coppola
Name: 1, dtype: object

In [16]:
df[df['rating']>=9]

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
5,6,Schindler's List,1993,9.0,"Biography,Drama,History",R,3h 15m,"Whoever saves one life, saves the world entire.",22000000,322161245,"Liam Neeson,Ralph Fiennes,Ben Kingsley,Carolin...",Steven Spielberg,"Thomas Keneally,Steven Zaillian"
6,7,The Lord of the Rings: The Return of the King,2003,9.0,"Action,Adventure,Drama",PG-13,3h 21m,The eye of the enemy is moving.,94000000,1146457748,"Elijah Wood,Viggo Mortensen,Ian McKellen,Orlan...",Peter Jackson,"J.R.R. Tolkien,Fran Walsh,Philippa Boyens"

In [25]:
df[df['rating']<=8]

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
226,227,The Incredibles,2004,8.0,"Animation,Action,Adventure",PG,1h 55m,Save The Day,92000000,631607053,"Craig T. Nelson,Samuel L. Jackson,Holly Hunter...",Brad Bird,Brad Bird
243,244,Life of Brian,1979,8.0,Comedy,R,1h 34m,A motion picture destined to offend nearly two...,4000000,20745728,"Graham Chapman,John Cleese,Michael Palin,Terry...",Terry Jones,"Graham Chapman,John Cleese,Terry Gilliam"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [32]:
df.set_index('rank',inplace=True) 
df

KeyError: "None of ['rank'] are in the columns"

In [33]:
df.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            241, 242, 243, 244, 245, 246, 247, 248, 249, 250],
           dtype='int64', name='rank', length=250)

In [27]:
for rating in df:
    print(f'{rating}=> {df[rating].nsmallest()}') #! want smallest number in the column of df rating

rank=> 0    1
1    2
2    3
3    4
4    5
Name: rank, dtype: int64

TypeError: Cannot use method 'nsmallest' with dtype object

In [39]:
ug=df.genre.nunique()
ug

104

In [45]:
sr=df.sort_values(by='rating',ascending=False)
#df.head()
sr

,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
rank,,,,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...
227,The Incredibles,2004,8.0,"Animation,Action,Adventure",PG,1h 55m,Save The Day,92000000,631607053,"Craig T. Nelson,Samuel L. Jackson,Holly Hunter...",Brad Bird,Brad Bird
244,Life of Brian,1979,8.0,Comedy,R,1h 34m,A motion picture destined to offend nearly two...,4000000,20745728,"Graham Chapman,John Cleese,Michael Palin,Terry...",Terry Jones,"Graham Chapman,John Cleese,Terry Gilliam"
248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [47]:
cols_to_drops = ['budget','box_office','certificate']
df.drop(columns=cols_to_drops)

,name,year,rating,genre,run_time,tagline,casts,directors,writers
rank,,,,,,,,,
1,The Shawshank Redemption,1994,9.3,Drama,2h 22m,Fear can hold you prisoner. Hope can set you f...,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
2,The Godfather,1972,9.2,"Crime,Drama",2h 55m,An offer you can't refuse.,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
3,The Dark Knight,2008,9.0,"Action,Crime,Drama",2h 32m,Why So Serious?,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
4,The Godfather Part II,1974,9.0,"Crime,Drama",3h 22m,All the power on earth can't change destiny.,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
5,12 Angry Men,1957,9.0,"Crime,Drama",1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...
246,The Help,2011,8.1,Drama,2h 26m,Change begins with a whisper.,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",2h 22m,There is man and beast at nature's mercy. Ther...,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",1h 30m,Wish granted! (DVD re-release),"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
249,Gandhi,1982,8.0,"Biography,Drama,History",3h 11m,His Triumph Changed The World Forever.,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",3h 1m,Inside everyone is a frontier waiting to be di...,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake